# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6536b1bbeaa02035ebc9b3f3058294e48970e317717bc6fc0d2c56505443e2dc7e86fa194304fc3e57c820a0fd86ff0f4a8f14793ead4ac764d45998249cf83c

test:
  secret_key_base: 342b5fd798fea261296dbcf6715a7da015633eb47dfc0db8f630fe4356c566c21f348694cd984fbee2449156ca26945906045df48186e874af62de29ff215149

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
